In [1]:
import pandas as pd
import numpy as np
import os

In [7]:
filename:str=r'/Volumes/WD_BLACK/DATA/EXPORT/buoy_obs_all_cleaned_260120_02.h5'

In [8]:
store=pd.HDFStore(filename, mode='r')

In [9]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: /Volumes/WD_BLACK/DATA/EXPORT/buoy_obs_all_cleaned_260120_02.h5

In [10]:
store.keys()

['/MF01001', '/MF01002', '/MF01004']

In [11]:
pd.read_hdf(store, key='/MF01001')

,Buoy_ID,Lat_Decimal,Lon_Decimal,Obs_U,Obs_V,WS,WD
Obs_Time,,,,,,,
2023-12-31 16:00:00,MF01001,39.500333,120.595167,-8.722174,-5.664246,10.4,57.0
2023-12-31 17:00:00,MF01001,39.500000,120.594667,-7.958909,-6.218181,10.1,52.0
2023-12-31 18:00:00,MF01001,39.500333,120.594667,-6.549397,-4.417624,7.9,56.0
2023-12-31 19:00:00,MF01001,39.500500,120.595167,-5.207496,-4.526807,6.9,49.0
2023-12-31 20:00:00,MF01001,39.500500,120.595000,-3.959553,-4.100237,5.7,44.0
...,...,...,...,...,...,...,...
2024-12-31 11:00:00,MF01001,39.503000,120.609667,12.406827,-1.523367,12.5,277.0
2024-12-31 12:00:00,MF01001,39.503000,120.609667,11.692441,-2.699413,12.0,283.0
2024-12-31 13:00:00,MF01001,39.503000,120.609667,10.601574,-2.060737,10.8,281.0
2024-12-31 14:00:00,MF01001,39.503167,120.609667,9.158712,-1.614928,9.3,280.0
2024-12-31 15:00:00,MF01001,39.503333,120.609500,8.607699,-1.829623,8.8,282.0

In [12]:
pd.read_hdf(store, key='/MF01002')

,Buoy_ID,Lat_Decimal,Lon_Decimal,Obs_U,Obs_V,WS,WD
Obs_Time,,,,,,,
2023-12-31 16:00:00,MF01002,39.033333,120.083333,-9.665301,-4.102677,10.5,67.0
2023-12-31 17:00:00,MF01002,39.033333,120.083333,-7.784115,-4.314806,8.9,61.0
2023-12-31 18:00:00,MF01002,39.033333,120.083333,-8.494120,-1.345336,8.6,81.0
2023-12-31 19:00:00,MF01002,39.033333,120.083333,-6.889100,1.717645,7.1,104.0
2023-12-31 20:00:00,MF01002,39.033333,120.083333,-5.072794,-2.811896,5.8,61.0
...,...,...,...,...,...,...,...
2024-12-31 11:00:00,MF01002,NaN,NaN,6.733823,0.946377,6.8,262.0
2024-12-31 12:00:00,MF01002,39.033333,120.083333,5.610850,-5.418335,7.8,314.0
2024-12-31 13:00:00,MF01002,39.033333,120.083333,6.996837,-2.409204,7.4,289.0
2024-12-31 14:00:00,MF01002,39.033333,120.083333,6.181925,-1.656442,6.4,285.0
2024-12-31 15:00:00,MF01002,39.035000,120.083333,4.455033,-2.269952,5.0,297.0

In [13]:
pd.read_hdf(store, key='/MF01004')

,Buoy_ID,Lat_Decimal,Lon_Decimal,Obs_U,Obs_V,WS,WD
Obs_Time,,,,,,,
2023-12-31 16:00:00,MF01004,37.957167,119.860167,-6.330190,-6.112994,8.8,46.0
2023-12-31 17:00:00,MF01004,37.957167,119.860167,-3.813520,-7.484455,8.4,27.0
2023-12-31 18:00:00,MF01004,37.957167,119.860167,-2.409204,-6.996837,7.4,19.0
2023-12-31 19:00:00,MF01004,37.957333,119.860000,-2.717901,-5.572523,6.2,26.0
2023-12-31 20:00:00,MF01004,37.957333,119.860000,-0.512189,-4.873157,4.9,6.0
...,...,...,...,...,...,...,...
2024-12-31 11:00:00,MF01004,0.000000,0.000000,3.864353,3.479479,5.2,228.0
2024-12-31 12:00:00,MF01004,37.955000,119.897000,5.096807,3.703047,6.3,234.0
2024-12-31 13:00:00,MF01004,0.000000,0.000000,4.095760,2.867882,5.0,235.0
2024-12-31 14:00:00,MF01004,37.955000,119.896667,5.932041,2.893250,6.6,244.0
2024-12-31 15:00:00,MF01004,37.955000,119.897000,6.000171,3.605267,7.0,239.0